### ลงนามเอกสาร
POST http://localhost:8081/documents/2/sign
Content-Type: application/json

{
  "requesterId": 2,
  "providerId": 1,
  "comment": "ลงนามแล้วเรียบร้อย",
  "status": "SIGNED"
}

###

### แก้ไขเอกสาร
POST http://localhost:8081/documents/2/edit
Content-Type: application/json

{
  "requesterId": 2,
  "editorId": 4,
  "editCommand": "เปลี่ยนชื่อผู้รับเป็น Tantawan"
}

###