#ขอลงนาม (ผ่าน Request Service)
POST http://localhost:8080/request/sign
Content-Type: application/json

{
  "documentId": 1,
  "requester": "User B"
}

###

#แก้ไขเอกสาร
POST http://localhost:8080/request/edit
Content-Type: application/json

{
  "documentId": 2,
  "reason": "เปลี่ยนชื่อผู้รับเป็น Tantawan"
}