### 2. ลงนามเอกสาร (SIGNATURE)
POST http://localhost:8080/api/sign
Content-Type: application/json

{
  "requesterId": 2,
  "providerId": 1,
  "documentId": 2,        
  "comment": "ลงนามแล้วเรียบร้อย",
  "status": "SIGN"
}


### 4. ขอให้แก้ไขเอกสาร (EDIT) 
POST http://localhost:8080/api/edit
Content-Type: application/json

{
  "requesterId": 2,
  "editorId":    4,
  "documentId":  2,
  "editCommand": "เปลี่ยนชื่อผู้รับเป็น Tantawan"
}


