CREATE TABLE USERS (
  ID INT PRIMARY KEY,
  ACTIVE BOOLEAN NOT NULL,
  CREATED_AT TIMESTAMP,
  EMAIL VARCHAR(255),
  NAME VARCHAR(255),
  UPDATED_AT TIMESTAMP
);

CREATE TABLE DOCUMENT (
  ID INT PRIMARY KEY,
  CONTENT TEXT,
  STATUS VARCHAR(50),
  TITLE VARCHAR(255),
  OWNER_ID INT,
  SIGNED_AT TIMESTAMP,
  SIGNED_BY INT,
  FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID),
  FOREIGN KEY (SIGNED_BY) REFERENCES USERS(ID)
);

CREATE TABLE SERVICE_REQUEST (
  ID INT PRIMARY KEY,
  DESCRIPTION TEXT,
  SERVICE_TYPE VARCHAR(50),
  STATUS VARCHAR(50),
  TIMESTAMP TIMESTAMP,
  DOCUMENT_ID INT,
  PROVIDER_ID INT,
  REQUESTER_ID INT,
  FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT(ID),
  FOREIGN KEY (PROVIDER_ID) REFERENCES USERS(ID),
  FOREIGN KEY (REQUESTER_ID) REFERENCES USERS(ID)
);